---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bb-app
  namespace: 1-demo
spec:
  interval: 1h0m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: bb-app
  timeout: 3m0s
  wait: true
