apiVersion: v1
kind: Namespace
metadata:
  name: 1-demo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bb-app
  namespace: 1-demo
spec:
  interval: 1m0s
  ref:
    branch: 1-demo
  url: https://github.com/singhkgurtej/bb-app-source.git
